export {default as SectionSponsored} from '~/components/common/SectionSponsored'
export {default as SectionPrincipalComponent} from '~/components/common/SectionPrincipalComponent'
export {default as SectionCategoriesComponent} from '~/components/common/SectionCategoriesComponent'
export {default as SectionRelatedComponent} from '~/components/common/SectionRelatedComponent'
export {default as TournamentsFiltered} from '~/components/common/TournamentsFiltered'
export {default as TournamentDetails} from '~/components/common/TournamentDetails'
