export {default as FooterComponent} from '~/components/common/FooterComponent'
export {default as SectionSearchComponent} from '~/components/common/SectionSearchComponent'
export {default as ArticleTournamentComponent} from '~/components/common/ArticleTournamentComponent'
export {default as SectionPrincipalComponent} from '~/components/common/SectionPrincipalComponent'
export {default as SectionCategoriesComponent} from '~/components/common/SectionCategoriesComponent'
export {default as SectionRelatedComponent} from '~/components/common/SectionRelatedComponent'
export {default as HeaderComponent} from '~/components/common/HeaderComponent'
export {default as TournamentDetails} from '~/components/common/TournamentDetails'
