export {default as ArticleTournamentComponent} from '~/components/common/ArticleTournamentComponent'
export {default as CreateTournamentComponent} from '~/components/common/CreateTournamentComponent'
export {default as SectionPrincipalComponent} from '~/components/common/SectionPrincipalComponent'
export {default as SectionCategoriesComponent} from '~/components/common/SectionCategoriesComponent'
export {default as SectionRelatedComponent} from '~/components/common/SectionRelatedComponent'
export {default as TournamentDetails} from '~/components/common/TournamentDetails'
